version: '3.7'

services:
  ffc-ce-admin-web:
    build: .
    image: ffc-ce-admin-web
    command: npm run start:watch
    environment:
      ACTIONS_URL: http://ffc-ce-payment-orchestrator:3002
      COOKIE_PASSWORD: aPasswordNotUsedAnywhereOnlyLocallyWhenTesting
    ports:
      - "3001:3000"
    volumes:
      - ./client/:/usr/src/app/client/
      - ./server/:/usr/src/app/server/
      - ./index.js:/usr/src/app/index.js
      - ./package.json:/usr/src/app/package.json
