{{- define "ffc-ce-admin-web.container" -}}
env:
- name: NODE_ENV
  value: {{ quote .Values.environment }}
- name: PORT
  value: {{ quote .Values.container.port }}
- name: ACTIONS_URL
  value: {{ quote .Values.container.actionsUrl }}
- name: COOKIE_PASSWORD
  value: {{ quote .Values.container.cookiePassword }}
- name: REST_CLIENT_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.restClientTimeoutMillis }}
- name: STATIC_CACHE_TIMEOUT_IN_MILLIS
  value: {{ quote .Values.container.staticCacheTimeoutMillis }}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
livenessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.livenessProbe) | nindent 4 }}
readinessProbe: {{ include "ffc-helm-library.http-get-probe" (list . .Values.readinessProbe) | nindent 4 }}
{{- end -}}
